// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKkyLUyCgBEWOfq0Gs7Yfv5FLWiZgVV1I',
    appId: '1:853054702494:web:2ef7570d055f0a0ba30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    authDomain: 'docbooking-9ec13.firebaseapp.com',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    measurementId: 'G-KFS6C3HXGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA2yNxEEZ2QKHWnEuUsxOiDH9Yv74ZHko',
    appId: '1:853054702494:android:bbfe0a3c74019a5da30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG7wTqlePvOwOGZ5IhL9YFC2krgYsIoSw',
    appId: '1:853054702494:ios:ea656277bfcb41c1a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    androidClientId: '853054702494-1g1d431p6vmsl4kuvstfr49bkroujtou.apps.googleusercontent.com',
    iosClientId: '853054702494-n9h4qgmubj517g98pkl9063r1g6084aj.apps.googleusercontent.com',
    iosBundleId: 'com.quadvare.zappqAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG7wTqlePvOwOGZ5IhL9YFC2krgYsIoSw',
    appId: '1:853054702494:ios:082f95da5a6ab73da30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    androidClientId: '853054702494-1g1d431p6vmsl4kuvstfr49bkroujtou.apps.googleusercontent.com',
    iosClientId: '853054702494-at79r2mvjgo2hgqqq1rg4v89u24hbmvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.zappqAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKkyLUyCgBEWOfq0Gs7Yfv5FLWiZgVV1I',
    appId: '1:853054702494:web:2ef7570d055f0a0ba30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    authDomain: 'docbooking-9ec13.firebaseapp.com',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    measurementId: 'G-KFS6C3HXGR',
  );

}